// src/Menubar/index.jsx
import Style from "./Menubar.module.css";
import { onMount, onCleanup, createSignal, createEffect } from "solid-js";
import { ParseFileString } from "../FileManager";
import {
	ISOCodeList,
	Endonyms,
	EndonymToCode,
} from "../Localization/Languages";
import Dict from "../Localization/dictionary.json";

const allViews = ["crease pattern", "simulator", "diagram"];
let inputFileRef;

const Hamburger = (props) => <ul>
	<li>
		<svg
			class="hamburger-svg"
			width="1.3rem"
			height="1.3rem"
			viewBox="0 0 20 20"
			stroke-width="4"
			stroke-linecap="round"
			stroke={props.darkMode() ? "#ccc" : "black"}>
			<line x1="3" y1="4" x2="17" y2="4"/>
			<line x1="3" y1="10" x2="17" y2="10"/>
			<line x1="3" y1="16" x2="17" y2="16"/>
		</svg>
		{props.children}
	</li>
</ul>;

const Navbar = (props) => {

	// translation
	const [T, setT] = createSignal(s => s);
	createEffect(() => {
		const newT = (s) => Dict[s] && Dict[s][props.language()] ? Dict[s][props.language()] : s;
		setT(() => newT);
	});

	return <ul>
		<li>{T()("file")}
			<ul>
				<li onClick={() => props.setShowNewPopup(true)}>{T()("new")}</li>
				<li onClick={() => inputFileRef.click()}>{T()("open")}</li>
				<li onClick={props.saveFile}>{T()("save")}</li>
			</ul>
		</li>
		<li>{T()("view")}
			<ul>
				<For each={allViews}>{(view) =>
					<li
						class={`menu-view-${view}`}
						highlighted={props.views().includes(view)}
						onClick={() => props.onClickView(view)}>{T()(view)}</li>
				}</For>
				<hr />
				<li
					onClick={() => props.setShowTerminal(!props.showTerminal())}
					highlighted={props.showTerminal().toString()}
				>{T()("show terminal")}</li>
				<li
					onClick={() => props.setShowPanels(!props.showPanels())}
					highlighted={props.showPanels().toString()}
				>{T()("show panels")}</li>
			</ul>
		</li>
		<li>{T()("preferences")}
			<ul>
				<li
					onClick={() => props.setDarkMode(!props.darkMode())}
					highlighted={props.darkMode().toString()}
				>{T()("dark mode")}</li>
				<li
					onClick={() => props.setShowDebugPanel(!props.showDebugPanel())}
					highlighted={props.showDebugPanel().toString()}
				>{T()("debug panel")}</li>
			</ul>
		</li>
		<li>{T()(Endonyms[props.language()])}
			<ul>
				<For each={ISOCodeList.map(code => Endonyms[code])}>{(language) =>
					<li
						onClick={() => props.setLanguage(EndonymToCode[language])}
						highlighted={Endonyms[props.language()] === language}
					>{language}</li>}
				</For>
			</ul>
		</li>

		<li>{T()("help")}
			<ul>
				<li onClick={() => props.setShowExamplesPopup(true)}>{T()("examples")}</li>
				<li onClick={() => {}}>{T()("about")}</li>
			</ul>
		</li>

	</ul>;
};


const Menubar = (props) => {

	const onClickView = (newView) => {
		const currentViews = props.views();
		if (currentViews.includes(newView)) {
			return props.setViews(currentViews.filter(a => a !== newView));
		} else {
			currentViews.push(newView);
			return props.setViews([...currentViews]);
		}
	};

	const fileDialogDidLoad = (string, filename, mimeType) => {
		const result = ParseFileString(string, filename, mimeType);
		if (result.error) { return props.setErrorMessage(result.error); }
		props.loadFile(result);
	};

	const fileDidLoad = (event) => {
		event.stopPropagation();
		event.preventDefault();
		// file reader and its callbacks
		let filename, mimeType;
		const reader = new FileReader();
		// reader.onerror = error => console.warn("FileReader error", error);
		// reader.onabort = abort => console.warn("FileReader abort", abort);
		reader.onload = loadEvent => fileDialogDidLoad(loadEvent.target.result, filename, mimeType);
		if (event.target.files.length) {
			mimeType = event.target.files[0].type;
			filename = event.target.files[0].name;
			return reader.readAsText(event.target.files[0]);
		}
		console.warn("FileReader no file selected");
	};

	const Nav = () => <Navbar
		setShowNewPopup={props.setShowNewPopup}
		setShowExamplesPopup={props.setShowExamplesPopup}
		saveFile={props.saveFile}
		views={props.views}
		darkMode={props.darkMode}
		setDarkMode={props.setDarkMode}
		language={props.language}
		setLanguage={props.setLanguage}
		showPanels={props.showPanels}
		setShowPanels={props.setShowPanels}
		showTerminal={props.showTerminal}
		setShowTerminal={props.setShowTerminal}
		onClickView={onClickView}
		// debug
		showDebugPanel={props.showDebugPanel}
		setShowDebugPanel={props.setShowDebugPanel}
	/>;

	return (<>
		<nav class={Style.Menubar}>
			<Show when={props.mobileLayout()}>
				<Hamburger darkMode={props.darkMode}>
					<Nav />
				</Hamburger>
			</Show>
			<Show when={!props.mobileLayout()}>
				<Nav />
			</Show>
			<input
				type="file"
				id="file"
				ref={inputFileRef}
				onChange={fileDidLoad.bind(this)} />
		</nav>
	</>);
};

export default Menubar;

// src/components/Menubar.svelte
<script lang="ts">
	import Languages from "../data/languages.json";
	export let views = [];

	const allViews = ["crease pattern", "simulator", "folded form"]
	const languages = Object.values(Languages)
		.map(el => el.name);
	const setShowNewPopup = () => {};
	const saveFile = () => {};
	const setShowExamplesPopup = () => {};

	const onClickView = (newView) => {
		views = views.includes(newView)
			? views.filter(a => a !== newView)
			: [ ...views, newView ];
	};
	export let showTerminal = false;
	export let showPanels = false;
	export let showDebugPanel = false;
	export let darkMode = false;
	let language = "english";

</script>

	<nav>
		<ul>
			<li>file
				<ul>
					<li on:click={() => setShowNewPopup(true)}>new</li>
					<li on:click={() => {}}>open</li>
					<li on:click={saveFile}>save</li>
				</ul>
			</li>
			<li>view
				<ul>
					{#each allViews as view}
						<li
							class={`menu-view-${view}`}
							highlighted={views.includes(view)}
							on:click={() => onClickView(view)}>{view}</li>
					{/each}
					<hr />
					<li
						on:click={() => { showTerminal = !showTerminal; }}
						highlighted={showTerminal}
					>show terminal</li>
					<li
						on:click={() => { showPanels = !showPanels; }}
						highlighted={showPanels}
					>show panels</li>
				</ul>
			</li>
			<li>preferences
				<ul>
					<li
						on:click={() => { darkMode = !darkMode; }}
						highlighted={darkMode}
					>dark mode</li>
					<li
						on:click={() => { showDebugPanel = !showDebugPanel; }}
						highlighted={showDebugPanel}
					>debug panel</li>
				</ul>
			</li>
			<li>language
				<ul>
					{#each languages as lang}
						<li
							on:click={() => language = lang}
							highlighted={lang === language}
						>{lang}</li>
					{/each}
				</ul>
			</li>
			<li>help
				<ul>
					<li on:click={() => setShowExamplesPopup(true)}>examples</li>
					<li on:click={() => {}}>about</li>
				</ul>
			</li>
		</ul>
	</nav>

<style>
	:global(.light-mode) {
		--menu-bg-color: white;
		--menu-text-color: black;
		--menu-border-color: #fb4;
		--menu-shadow-color: rgba(0, 0, 0, 0.25);
		--menu-highlight-color: #e53;
		--menu-select-color: #fb4;
	}
	:global(.dark-mode) {
		--menu-bg-color: var(--darkmode-gray-2);
		--menu-text-color: var(--darkmode-gray-9);
		--menu-border-color: var(--darkmode-blue-dark);
		--menu-shadow-color: black;
		--menu-highlight-color: var(--darkmode-blue);
		--menu-select-color: var(--darkmode-blue-dark);
	}
	nav {
		font-weight: 700;
		font-size: var(--app-font-size);
		height: var(--menubar-height);
		border-bottom: var(--menubar-border-width) solid var(--menu-border-color);
	}
	nav ul {
		padding: 0;
		margin: 0;
		list-style: none;
	}
	nav li {
		margin-left: 0;
	}
	nav hr {
		margin: 0.25rem auto;
		width: 90%;
	}
	nav > ul {
		height: 100%;
/*		background-color: #eee; this was in light mode. why?*/
	}
	nav > ul > li {
		display: inline-flex; /* inline-block */
		align-items: center;
	}
	nav li {
		padding: 0 1rem;
		cursor: pointer;
		height: 100%;
	}
	nav ul ul li {
		padding: 0.25rem 1rem;
	}
	nav ul ul li.menubar-view-item {
		padding: 0 1rem;
	}
	nav,
	nav ul ul {
		background-color: var(--menu-bg-color);
		color: var(--menu-text-color);
	}
	nav ul ul {
		display: none;
		position: absolute;
		z-index: 3;
		top: calc(var(--menubar-height) - var(--menubar-border-width));
		box-shadow:
			0
			calc(var(--app-font-size) * 0.5)
			var(--app-font-size)
			0
			var(--menu-shadow-color);
	}
	nav ul ul li {
		position: relative;
	}
	nav ul ul ul {
		top: 0px;
		left: calc(var(--app-font-size) * 6);
	}
	nav li:hover > ul {
		display: block;
	}
	/*file open hidden input dialog trigger*/
	nav input {
		display: none;
	}
	nav li[highlighted=true] {
		background-color: var(--menu-highlight-color);
		color: white;
	}
	nav li:hover {
		background-color: var(--menu-select-color);
		color: white;
	}
</style>
